version: '3.3'

services:
  # Postgres
  dbase:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  web:
    build: .
    command: ["/app/run_web.sh"]

    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - dbase
    depends_on:
      - dbase
