# Generated by Django 3.0.6 on 2020-05-31 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da reunião')),
                ('description', models.TextField(max_length=500, verbose_name='Descrição')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Data')),
                ('image', models.ImageField(upload_to='', verbose_name='Imagem de referência')),
                ('participants', models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL, verbose_name='Participantes')),
            ],
            options={
                'verbose_name': 'Reunião',
                'verbose_name_plural': 'Reuniões',
            },
        ),
    ]
