# Generated by Django 3.0.6 on 2020-05-31 20:14

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='Data'),
        ),
    ]
