# Generated by Django 3.0.6 on 2020-06-03 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200602_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ('-date',), 'verbose_name': 'Reunião', 'verbose_name_plural': 'Reuniões'},
        ),
    ]
